#include "ctype.h"

const unsigned char __ctype_table[128] = {
    /* 0x00-0x07 */ 0,0,0,0,0,0,0,0,
    /* 0x08-0x0F */ 0,__CTYPE_SPACE,__CTYPE_SPACE,__CTYPE_SPACE,__CTYPE_SPACE,__CTYPE_SPACE,0,0,
    /* 0x10-0x17 */ 0,0,0,0,0,0,0,0,
    /* 0x18-0x1F */ 0,0,0,0,0,0,0,0,
    /* 0x20-0x27 */ __CTYPE_SPACE,0,0,0,0,0,0,0,
    /* 0x28-0x2F */ 0,0,0,0,0,0,0,0,
    /* 0x30-0x37 */ __CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,
                   __CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,
    /* 0x38-0x3F */ __CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,0,0,0,0,0,0,
    /* 0x40-0x47 */ 0,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,
                   __CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER,
    /* 0x48-0x4F */ __CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,
    /* 0x50-0x57 */ __CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,
    /* 0x58-0x5F */ __CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,0,0,0,0,0,
    /* 0x60-0x67 */ 0,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,
                   __CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER,
    /* 0x68-0x6F */ __CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,
    /* 0x70-0x77 */ __CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,
    /* 0x78-0x7F */ __CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,0,0,0,0,0
};

