/*
 * BSD 2-Clause License: Redistribution and use in source and binary forms, with or without modification, are permitted provided that the copyright notice and this permission notice appear in all copies. This software is provided "as is" without warranty.
 *
 * Purpose: Implements the ctype functions for vlibc. Provides wrappers and helpers used by the standard library.
 *
 * Copyright (c) 2025
 */

#include "ctype.h"

const unsigned char __ctype_table[128] = {
    /* 0x00-0x07 */ __CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,
    /* 0x08-0x0F */ __CTYPE_CNTRL,__CTYPE_CNTRL|__CTYPE_SPACE|__CTYPE_BLANK,__CTYPE_CNTRL|__CTYPE_SPACE,__CTYPE_CNTRL|__CTYPE_SPACE,__CTYPE_CNTRL|__CTYPE_SPACE,__CTYPE_CNTRL|__CTYPE_SPACE,__CTYPE_CNTRL,__CTYPE_CNTRL,
    /* 0x10-0x17 */ __CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,
    /* 0x18-0x1F */ __CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,__CTYPE_CNTRL,
    /* 0x20-0x27 */ __CTYPE_SPACE|__CTYPE_BLANK,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,
    /* 0x28-0x2F */ __CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,
    /* 0x30-0x37 */ __CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,
    /* 0x38-0x3F */ __CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_DIGIT|__CTYPE_XDIGIT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,
    /* 0x40-0x47 */ __CTYPE_PUNCT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER|__CTYPE_XDIGIT,__CTYPE_UPPER,
    /* 0x48-0x4F */ __CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,
    /* 0x50-0x57 */ __CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,
    /* 0x58-0x5F */ __CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_UPPER,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,
    /* 0x60-0x67 */ __CTYPE_PUNCT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER|__CTYPE_XDIGIT,__CTYPE_LOWER,
    /* 0x68-0x6F */ __CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,
    /* 0x70-0x77 */ __CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,
    /* 0x78-0x7F */ __CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_LOWER,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_PUNCT,__CTYPE_CNTRL
};

